// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5Ugsm8talDx3cwN7O4oiTqFFRkXL9HIk',
    appId: '1:513171410508:web:81cb9f26c20de817d12ee9',
    messagingSenderId: '513171410508',
    projectId: 'congelper',
    authDomain: 'congelper.firebaseapp.com',
    storageBucket: 'congelper.firebasestorage.app',
    measurementId: 'G-3J5E24161Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdI5T-k5FttoLbuc5JjFykg0PImiFePvc',
    appId: '1:513171410508:android:d9736ad147490c62d12ee9',
    messagingSenderId: '513171410508',
    projectId: 'congelper',
    storageBucket: 'congelper.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsCVs4Hiv-dQEq2JhYTkmNOZWwh1eyaFw',
    appId: '1:513171410508:ios:5af9bcfbf389bdeed12ee9',
    messagingSenderId: '513171410508',
    projectId: 'congelper',
    storageBucket: 'congelper.firebasestorage.app',
    iosBundleId: 'com.runcode.congelper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsCVs4Hiv-dQEq2JhYTkmNOZWwh1eyaFw',
    appId: '1:513171410508:ios:5af9bcfbf389bdeed12ee9',
    messagingSenderId: '513171410508',
    projectId: 'congelper',
    storageBucket: 'congelper.firebasestorage.app',
    iosBundleId: 'com.runcode.congelper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5Ugsm8talDx3cwN7O4oiTqFFRkXL9HIk',
    appId: '1:513171410508:web:6223c733744af96cd12ee9',
    messagingSenderId: '513171410508',
    projectId: 'congelper',
    authDomain: 'congelper.firebaseapp.com',
    storageBucket: 'congelper.firebasestorage.app',
    measurementId: 'G-EY11ZKVFQX',
  );

}